[package]
name = "sand"
version = "0.1.0"
edition = "2021"

[dependencies]
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
clap = { version = "4.5.13", features = ["derive"] }
dirs = "5.0.1"
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }
