name = "timer"
defaultTargets = ["timer"]

[[lean_lib]]
name = "Timer"

[[lean_exe]]
name = "timer"
root = "TimerClient"

[[lean_exe]]
name = "timerd"
root = "TimerDaemon"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.8.0"

[[require]]
name = "socket"
# git = "https://github.com/hargoniX/socket.lean"
git = "/home/james/dev/socket.lean"
rev = "main"
