name = "timer"
defaultTargets = ["sand", "sandd"]

[[lean_lib]]
name = "Sand"

[[lean_exe]]
name = "sand"
root = "SandClient"

[[lean_exe]]
name = "sandd"
root = "SandDaemon"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.9.1"

[[require]]
name = "socket"
git = "https://github.com/hargoniX/socket.lean"
rev = "main"
