name = "timer"
defaultTargets = ["timer"]

[[lean_lib]]
name = "Timer"

[[lean_exe]]
name = "timer"
root = "Main"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.9.0"
