name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      # needed for action-gh-release
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v2
      - run: |
          export DEBIAN_FRONTEND=noninteractive 
          sudo apt-get install libasound2-dev
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          toolchain: nightly
      - run: cargo build --release
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run integration tests
        env:
          SAND_TEST_TARGET: release
        run: |
          echo "Testing $(target/release/sand version)"
          python -m pip install --upgrade pip
          pip install pytest
          pip install deepdiff
          pytest test.py