name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: "true"
      - name: Run Lean Action
        uses: leanprover/lean-action@v1
        with:
          auto-config: "false"
          use-mathlib-cache: "false"
          build: "true"
      - name: Create package
        id: create-package
        run: |
          ./create_release.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          path: release/sand-*-x86_64-linux.tar.zst
