name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lean Action
        uses: leanprover/lean-action@v1
        with:
          auto-config: "false"
          use-mathlib-cache: "false"
          build: "true"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run integration tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest test_daemon.py

      # - name: Create package
      #   run: |
      #     ./create_release.sh
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4.3.4
      #   with:
      #     name: sand
      #     path: release/sand-x86_64-linux.tar.zst
