name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lean Action
        uses: leanprover/lean-action@v1
      - name: Create archive
        run: |
          mkdir artefacts
          cp .lake/build/bin/sand .lake/build/bin/sandd artefacts/
          tar --create --gzip --file binaries.tar.gz -C artefacts .
      - name: Upload binaries
        uses: actions/upload-artifact@v4.3.4
        with:
          name: binaries-archive
          path: binaries.tar.gz
