name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lean Action
        uses: leanprover/lean-action@v1
        with:
          auto-config: "false"
          use-mathlib-cache: "false"
          build: "true"
      - name: Create package
        # todo parameterize version
        run: |
          RELEASE_DIR=sand-release
          mkdir -p $RELEASE_DIR
          env PREFIX="$RELEASE_DIR" ./install.sh
          RELEASE_ARCHIVE=sand-x86_64-linux.tar.zst
          tar --zstd -cvf "$RELEASE_ARCHIVE" "$RELEASE_DIR"
          echo "release archive created at $RELEASE_ARCHIVE"
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: sand
          path: sand-x86_64-linux.tar.zst
