name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lean Action
        uses: leanprover/lean-action@v1
        with:
          auto-config: "false"
          use-mathlib-cache: "false"
          build: "true"
      - name: Create package
        run: |
          ./create_release.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: sand
          path: release/
