name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      # needed for action-gh-release
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lean Action
        uses: leanprover/lean-action@v1
        with:
          auto-config: "false"
          use-mathlib-cache: "false"
          build: "true"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run integration tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest test_daemon.py

      - name: Create release archive
        run: ./create_release_archive.sh
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: release/sand-x86_64-linux.tar.zst
